UI improved
NESS-Network/NVS-exchange pull request #1
Opened 2023-08-24 07:41 UTC by Frahane

![Screenshot_20230802-145127](https://github.com/NESS-Network/NVS-exchange/assets/46817735/e04af4a4-2a5d-41a7-9f5e-07050d4982fb)

2023-09-12 20:21 UTC, Alex014 requested changes

2023-09-12 20:21 UTC, Alex014 commented on web/exchange-form-slot.php
> -
We need this part

2023-09-13 21:18 UTC, Frahane commented on web/exchange-form-slot.php
> -
Understood!

2023-09-14 08:42 UTC, Frahane commented on web/exchange-form-slot.php
> -
Done. It was removed by mistake. Sorry.
Please, let me know if there's any other. ☺️

2023-09-28 14:28 UTC, Alex014 approved these changes
Ok on a first look
Needs to be tested

2023-09-28 14:28 UTC, Alex014 commented on web/exchange-form-slot.php
> -
(slot processing)

2023-09-28 14:41 UTC, merged